name: portainer
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'