shared_buffers = 512MB
effective_cache_size = 2GB
maintenance_work_mem = 512MB
work_mem = 16MB

checkpoint_completion_target = 0.9
#checkpoint_timeout = 5min

wal_buffers = 64MB
random_page_cost = 1.01
effective_io_concurrency = 200
#min_wal_size = 1GB
#max_wal_size = 8GB

wal_level = minimal
max_wal_senders = 0

#Kill and log any open transactions that do no queries for more than one minute.
#This usually means the software that opened the transaction has crashed,
#otherwise it should have issue a query or finished the transaction.
#Note: idle open transactions are bad because they prevent cleaning of dead tuples.
idle_in_transaction_session_timeout = 60s

# Doubled default value, may provide slight benefit (this is mainly for nvme drives)
io_combine_limit = 32
# Enable more parallel workers, allows speed up of index creation, especially hnsw indexes
max_worker_processes = 16
max_parallel_workers = 16

# Set to 4 to build indexes faster (code should temporarily increase this value further during index creation when possible)
max_parallel_maintenance_workers = 4
default_statistics_target = 500

#Changes based on pg_gather analysis, appears to improve sync performance by 10%,
#but post-analysis suggests more improvement via parameter tweaking is possible
bgwriter_lru_maxpages = 7000
checkpoint_timeout = 60min
min_wal_size = 128MB
max_wal_size = 2GB
