module.exports = [
    'https://api.hive.blog',
    'https://api.openhive.network',
    'https://anyx.io',
    'https://hived.privex.io',
    'https://hived.hive-engine.com',
    'https://hived.splinterlands.com',
    'https://direct.hived.privex.io',
    'https://api.pharesim.me',
    'https://rpc.ausbit.dev',
    'https://rpc.ecency.com',
    'https://hive.roelandp.nl',
    'https://api.c0ff33a.uk',
    'https://api.deathwing.me',
    'https://api.hive.blue',
    'https://hive-api.arcange.eu',
    'https://hived.emre.sh',
    'https://techcoderx.com'
]